### ISSUE TITLE
Fix voice connect

### ISSUE THREAD

**Issue by ToxicKidz** [asleep-cult/snekcord#18]
## Code
```py
fut = asyncio.Future()
async def client_connected(reader, writer):
    fut.set_result(reader)
    await evnt.send('made reader')
a = await asyncio.start_server(client_connected, '127.0.0.1', 8080)
_, writer = await asyncio.open_connection('127.0.0.1', 8080)
asyncio.get_event_loop().create_task(a.serve_forever())
voice_connection = await client.channels.get(772872533732753443).connect()
voice_connection.player = AudioPlayer(voice_connection, get_packets_encoded(await fut, voice_connection.loop))
voice_connection.receiver = AudioReceiver(voice_connection)
await asyncio.sleep(1)
await voice_connection.ws.send_speaking()
async def received(data):
    await writer.write(data)
voice_connection.receiver.voice_packet_received = received
await voice_connection.player.start(wait=False)
```
## Error
```py
Traceback (most recent call last):
  File "C:\Users\name\snakecord\snakecord_test_bot\bot.py", line 65, in listen
    voice_connection = await client.channels.get(772872533732753443).connect()
  File "C:\Users\name\snakecord\snakecord\snakecord\channel.py", line 92, in connect
    await shard.update_voice_state(self.guild.id, self.id)
AttributeError: 'Shard' object has no attribute 'update_voice_state'
```

**Comment by asleep-cult** [comment]
```py
from snakecord.audio.receive import AudioReceiver
from snakecord.audio.play import AudioPlayer
from snakecord.audio.packets import get_packets_encoded
fut = asyncio.Future()
async def client_connected(reader, writer):
    fut.set_result(reader)
    await message.channel.send('made reader')
a = await asyncio.start_server(client_connected, '127.0.0.1', 8080)
_, writer = await asyncio.open_connection('127.0.0.1', 8080)
asyncio.get_event_loop().create_task(a.serve_forever())
voice_connection = await client.channels.get(755487055794012236).connect()
voice_connection.player = AudioPlayer(voice_connection, get_packets_encoded(await fut, voice_connection.loop))
voice_connection.receiver = AudioReceiver(voice_connection)
await asyncio.sleep(1)
voice_connection.ws.set_speaking_state()
async def received(data):
    await writer.write(data)
voice_connection.receiver.voice_packet_received = received
await voice_connection.player.start(wait=False)
```

**Comment by ToxicKidz** [comment]
Thank you.
